
export enum ActionTypes {
    CREATE_CHECKOUT = 'CREATE_CHECKOUT',
    FETCH_CHECKOUT = 'FETCH_CHECKOUT',
    SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS', 
    ADD_TO_CART = "ADD_TO_CART",
    UPDATE_QUANTITY = "UPDATE_QUANTITY",
    DELETE_ITEM = "DELETE_ITEM",
    SET_PAGE_VALUE = "SET_PAGE_VALUE",
}